import type { Metadata } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';
import './globals.css';
import cn from 'classnames';

const inter = Inter({ subsets: ['latin-ext'], variable: '--font-inter' });
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin-ext'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(spaceGrotesk.variable, inter.variable)}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
