import type { Metadata } from 'next';
import { Inter, Archivo } from 'next/font/google';
import './globals.css';
import cn from 'classnames';

import Navbar from '@/app/components/navbar/Navbar';
import Footer from '@/app/components/Footer';

const inter = Inter({ subsets: ['latin-ext'], variable: '--font-inter' });
const spaceGrotesk = Archivo({
  subsets: ['latin-ext'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(spaceGrotesk.variable, inter.variable)}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
